class PlayerService:
    """Service to handle playback of recorded flows with AI enhancement"""

    def execute_step(self, step, use_ai_data=False, context_data=None, standard_data=None, page=None):
        """
        Execute a single step of a recorded flow

        Args:
            step: The step definition from the recorded flow
            use_ai_data: Whether to use AI-generated data
            context_data: Data generated by AI for context preservation
            standard_data: Standard test data from configuration
            page: Playwright page object
        """
        # Determine value source priority: context_data > standard_data > recorded_data
        if use_ai_data and context_data and step.get('field_name') in context_data:
            value = context_data.get(step.get('field_name'))
        elif standard_data and step.get('field_name') in standard_data:
            value = standard_data.get(step.get('field_name'))
        else:
            value = step.get('value')

        # Execute the step based on its type
        if step["type"] == "click":
            if page:
                page.click(step["selector"])
        elif step["type"] == "input":
            if page:
                page.fill(step["selector"], value)
        elif step["type"] == "select":
            if page:
                page.select_option(step["selector"], value=value)

    def replay_flow(self, flow, playback_mode="exact", page=None):
        """
        Replay an entire recorded flow

        Args:
            flow: The flow definition to replay
            playback_mode: "exact", "ai-enhanced", "hybrid", or "standard"
            page: Playwright page object
        """
        # Load configuration for standard data
        from backend.services.config_service import ConfigService
        config_service = ConfigService()
        standard_data = {
            "zipcode": config_service.get_property("standard.zipcode"),
            "phone": config_service.get_property("standard.phone")
        }

        # If using AI-enhanced mode, generate contextual data
        context_data = None
        if playback_mode == "ai-enhanced":
            from backend.services.llm_service import LLMService
            llm_service = LLMService()
            context_data = llm_service.generate_contextual_data(flow.get("steps", []))

        # Execute each step in the flow
        for step in flow.get("steps", []):
            self.execute_step(
                step=step,
                use_ai_data=(playback_mode == "ai-enhanced"),
                context_data=context_data,
                standard_data=standard_data,
                page=page
            )