[https://qa-ebenefits.benefit-test.com/fbmc]
username = prodsupport
password = Fbmc@dm1n$2016

[demo-site.com]
username = demo_user
password = SecurePass!1

[github.com]
username = test_dev_acc
password = fake_password_123
